### PR TITLE
Dev/lqr contro

### PR DESCRIPTION
**Pull request by juanmed**
Hi! I made the updates to the lqr controller as requested. 

Features added:

1) I created a control folder and all controllers will be there. Each controller has its run() method that executes it.
2) About making a controller parameters file for each controller, I dont think is necessary now. For readability and simplicity I think its better to leave all parameters in the file of each controller for now.
3) About the trajectories, the same as above: the waypoint generating methods are only 3, small and straight - forward. Maybe as we add more trajectories we can make a separate file.

Issues fixed:
 
1) I fixed some issues like the heading being invalid when velocity vector projection in x-y plane is zero.
2) The yawdot variable when generating a trajectory can get crazy values as >600rad/s. This is because delta_psi is divided by 0.005 indiscretely.  I tried to limit it to 5 rad/s for now. There is still some strange issue with heading computation, so finally I simply make both yaw and yawdot equal to zero. When done this way both the PID and LQR controllers can travel at least helix and polynomial waypoints. Leminiscata waypoints are still not possible with the PID controller but the LQR can do it.

There is still some things you requested that need to be done, but I need to focus on other stuff right now. I think is better done that perfect. 

Also please excuse if the quality of my pull request is not that good. I am new with git so learning as I go.

### CODE REVIEW

**Comment by hbd730** [comment]
Great work, sorry I did not have time this week to help you with snap
calculation question, but it is great that you work it out yourself. Sounds
exciting, I will check it out this weekend.

Yes the yaw rate has wrap around issue , It was a bit rush when I wrote
this code as I was preparing for an interview and really needs to get it
done quickly at that time.

Sounds like you play with traditional control theory a lot, there is some
advancement in deep reinforcement learning these days, check this out
https://github.com/harshitandro/RL-Quadcopter

It might be interesting to adapt to my own quad copter sometime to see if
it can do 3d trajectory rather than just straight takeoff.

Regards
Peter

**Comment by juanmed** [comment]
Hey thanks. Yes at some point I need to get into RL. By the way, I made other changes to graph inputs and system state. You can check at my fork of your repo on the dev/graphs branch. It records all data and graphs them in 2 .jpg pictures.

**Comment by hbd730** [comment]
Hi Juan,

I have merged your pr to dev/lqr-contro, but can you directly push code to
this branch in the future if you need? pull request is only needed when
merging your dev branch into master when it is ready.
Todo that I need to add you as contributor, could you tell me your github
email address?
When running your lqr, I also notice one thing that it does not seem to
settle well when reaching final goal position, could you explain that? It
also does not seems to go through the every desired waypoints before
interpolation.

Regards
Peter

**Comment by juanmed** [comment]
Hi! Thanks for accepting my changes. I plan to improve this branch as time allows. I sent you my email address, please check your email :)

Regarding the performance of the LQR controller, it is the expected performance of this controller. The main reasons are: 
1) The controller was designed using a model of the quadrotor that was linearized around the hover state. So thrust that are too far away from the hover thrust, or angular and linear accelerations that are too away from 0 will cause bad performance of the controller 
2) It was a assumed that the inertia tensor is a diagonal matrix (which it is not).

So when the state of the system is too far away from the hover state, the effect of the non linearities will be greater and the controller is not able to compensate for them. Also the fact that the inertia tensor is not actually diagonal will introduce coupling between rotation axis that is not accounted for in the model. You can see this in a real drone in the Fig 4 and 6 of the paper [1]. Here even after sliding mode control to account for the un-modelled effects, the hover control is not "perfect".  

S. L. Waslander, G. M. Hoffmann, Jung Soon Jang and C. J. Tomlin, "Multi-agent quadrotor testbed control design: integral sliding mode vs. reinforcement learning," 2005 IEEE/RSJ International Conference on Intelligent Robots and Systems, Edmonton, Alta., 2005, pp. 3712-3717.

**Pull request merged**
